#ifndef WFTILELAYERS_H

#define WFLAYER_GROUND 0
#define WFLAYER_GROUND2 1
#define WFLAYER_STRUCTURES 2
#define WFLAYER_STRUCTURES2 3
#define WFLAYER_STRUCTURES_IN_FRONT_OF_PLAYER 4
#define WFLAYER_STRUCTURES_IN_FRONT_OF_PLAYER2 5

#endif