#
#  Build an appimage using an ubuntu 20 based image and therefore an older glibc 
#  for maximum compatibility. Only build one configuration as an appimage.
#  instead of the full matrix as debian packages and windows files
#

name: AppImage CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
    - name: Install git
      run: |
        apt update
        apt install -y git
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Get Dependencies
      shell: bash
      run: |
        cd Stardew
        export DEBIAN_FRONTEND=noninteractive
        apt install -y curl wget python3 python3-pip build-essential libfuse2 libxml2 liblua5.3-dev libxml2-dev libbox2d-dev libglfw3-dev libfreetype-dev libopenal-dev libgtest-dev

        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

        wget https://github.com/Kitware/CMake/releases/download/v3.29.0/cmake-3.29.0-linux-x86_64.tar.gz
        tar xzf cmake-3.29.0-linux-x86_64.tar.gz -C /opt
        ln -s /opt/cmake-3.29.0-linux-x86_64/bin/cmake /usr/local/bin/cmake

        pip install jinja2
        source "$HOME/.cargo/env"
        cargo install nu --locked
    # - name: Stamp version
    #   run: | 
    #     cd Stardew
    #     ./Makefile.nu stamp_version false GLFW3 Release
        
    - name: Build
      run: |
        cd Stardew
        nu ./Makefile.nu build_linux Release OFF GLFW3 OPENGLES

    - name: Compile Assets
      run: |
        cd Stardew
        nu ./Makefile.nu compile_assets
    
    - name: Build appimage
      run: |
        cd Stardew
        nu ./Makefile.nu build_appimage
      
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact-appimage
        path: |
          Stardew/appimage/farming.AppImage

