# Build with the item definitions baked into the C executable.
# Runs a script to generate c source to set up item defs, based on xml data file
# item defs

name: Ubuntu CI - Baked in items

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: hustcer/setup-nu@v3
      with:
        version: "0.90" # Don't use 0.90 here, as it would be a float number and would be converted to 0.9, you can use v0.90/0.90.0 or '0.90'

    - name: Get Dependencies
      run: |
        cd Stardew
        bash GetDependencies.sh

    - name: Create version
      run: |
        cd Stardew/game
        python3 make_release_version_header.py 

    - name: Build
      run: |
        cd Stardew
        bash Build_Internal.sh Release OFF

    - name: Test
      run: |
        cd Stardew/build/enginetest
        ./StardewEngineTest

    - name: NetTest
      run: |
        cd Stardew
        sudo ./RunEngineNetTest.sh

    - name: Compile Assets
      run: |
        cd Stardew
        sudo ./compile_assets.sh

    - name: Build Debian Package
      run: |
        cd Stardew
        sudo ./BuildDebianPkg.sh
      
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: Stardew/*.deb

