name: Ubuntu CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: ["SDL2", "GLFW3"]
        baked: ["ON", "OFF"]
        type: ["Release", "Debug"]
        gl_api: ["OPENGL", "OPENGLES"]
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Get Dependencies
      run: |
        cd Stardew
        # for some reasom appimage tool needs this libfuse
        sudo apt install libfuse2t64 
        bash GetDependencies.sh

    - name: Stamp version
      env:
          BAKED: ${{ matrix.baked }}
      run: |
        cd Stardew/game
        if [ "$BAKED" = "ON" ]; then
          python3 make_release_version_header.py --platform ${{ matrix.platform }} --build_type ${{ matrix.type }} --baked
        else
          python3 make_release_version_header.py --platform ${{ matrix.platform }} --build_type ${{ matrix.type }}
        fi
        
    - name: Build
      run: |
        cd Stardew
        ./Build_Internal.sh ${{ matrix.type }} ${{ matrix.baked }} ${{ matrix.platform }} ${{ matrix.gl_api }} 

    - name: Compile Assets
      run: |
        cd Stardew
        sudo ./compile_assets.sh

    - name: Build Debian Package
      run: |
        cd Stardew
        sudo ./BuildDebianPkg.sh
    
    - name: Build appimage
      run: |
        cd Stardew
        sudo ./appimage/BuildAppImage.sh
      
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact-${{ matrix.baked }}-${{ matrix.platform }}-${{ matrix.type }} 
        path: |
          Stardew/*.deb

