name: Ubuntu CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: ["SDL2", "GLFW3"]
        baked: ["true", "false"]
        type: ["Release", "Debug"]
        gl_api: ["OPENGL", "OPENGLES"]
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: install nushell
      run: |
        sudo snap install nushell --classic

    - name: Get Dependencies
      run: |
        cd Stardew
        sudo ./Makefile.nu get_dependencies_apt

    - name: Stamp version
      env:
          BAKED: ${{ matrix.baked }}
      run: |
        cd Stardew
        ./Makefile.nu stamp_version $BAKED ${{ matrix.platform }} ${{ matrix.type }}
        
    - name: Build
      run: |
        cd Stardew
        ./Makefile.nu build_linux ${{ matrix.type }} ${{ matrix.baked }} ${{ matrix.platform }} ${{ matrix.gl_api }} 

    - name: Compile Assets
      run: |
        cd Stardew
        ./Makefile.nu compile_assets_linux

    - name: Build Debian Package
      run: |
        cd Stardew
        ./Makefile.nu build_debian
    
    - name: Build appimage
      run: |
        cd Stardew
        ./Makefile.nu build_appimage
      
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact-${{ matrix.baked }}-${{ matrix.platform }}-${{ matrix.type }} 
        path: |
          Stardew/*.deb
          Stardew/appimage/*.AppImage

