name: Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Conan
      uses: conan-io/setup-conan@v1
      with:
        audit_token: ${{ secrets.CONAN_AUDIT_TOKEN }}
        config_urls: |
          https://github.com/<org>/conan-config.git
          https://myrepo.com/conan-config.git

    - name: Install Conan dependencies
      run: |
        cd Stardew
        GetDependenciesConan.bat
    
    - name: Build
      run: |
        cd Stardew
        BuildRelease.bat

    - name: Test
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        Stardew/build/enginetest/StardewEngineTest.exe