name: Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: ["SDL2", "GLFW3"]
        baked: ["ON", "OFF"]
        type: ["Release", "Debug"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Conan
      uses: conan-io/setup-conan@v1

    - name: Install Conan dependencies
      run: |
        cd Stardew
        cmd /c "GetDependenciesConan.bat"

    - name: Stamp version
      env:
          BAKED: ${{ matrix.baked }}
      run: |
        cd Stardew/game
        if "%BAKED%"=="ON" (
            python make_release_version_header.py --platform ${{ matrix.platform }} --build_type ${{ matrix.type }} --baked
        ) else (
            python make_release_version_header.py --platform ${{ matrix.platform }} --build_type ${{ matrix.type }}
        )
        
    - name: Build
      run: |
        cd Stardew
        cmd /c "Build.bat" ${{ matrix.type }} ${{ matrix.baked }} ${{ matrix.platform }} 

    - name: Test
      run: |
        cd ./Stardew/build/enginetest/Release
        ./StardewEngineTest.exe

    - name: Compile Assets
      run: |
        cd Stardew
        cmd /c "compile_assets.bat"

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: Stardew/build/game/Release # or path/to/artifact
