name: Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Conan
      uses: conan-io/setup-conan@v1

    - name: Install Conan dependencies
      run: |
        cd Stardew
        cmd /c "GetDependenciesConan.bat"
    
    - name: Build
      run: |
        cd Stardew
        cmd /c "BuildRelease.bat"

    - name: Test
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ./Stardew/build/enginetest/Release/StardewEngineTest.exe